### ISSUE TITLE
isnt working anymore?

### ISSUE THREAD

**Issue by Soheab** [CedArctic/Chimera#19]
says this when i wanna start it 
![image](https://user-images.githubusercontent.com/33902984/49467197-2ccc2700-f802-11e8-84b0-75de0ae87e7e.png) it goes online but no commands works

**Comment by CedArctic** [comment]
Thanks for posting your issue. I haven't been able to replicate it by doing a fresh install using the instructions on Chimera's page. Did you run setup.bat and edited configs.py accordingly?

**Comment by Soheab** [comment]
> Thanks for posting your issue. I haven't been able to replicate it by doing a fresh install using the instructions on Chimera's page. Did you run setup.bat and edited configs.py accordingly?

ye i did everything but i didnt fill in the initial_path = "" thing is that needed? and what is it?

**Comment by CedArctic** [comment]
Try doing a fresh download of the project and setting it up again. In the
configs.py you only have to edit BOT_TOKEN and CHANNEL_ID.
