### ISSUE TITLE
Add a logo to the project

### ISSUE THREAD

**Issue by CedArctic** [CedArctic/Chimera#9]
TL;DR: Chimera is a local hosted Discord Bot to perform remote operations on your PC. It is written in simple Python and named after the Ancient Greek Mythology creature. The project needs a cool logo to be featured in the README file and elsewhere, can't wait to look at your submissions! 😄

Ready to contribute? See: https://github.com/CedArctic/Chimera#contributing

**Comment by Suraj1006** [comment]
Is the issue still open ?

**Comment by CedArctic** [comment]
@Suraj1006 Yup :)

**Comment by vlad4him** [comment]
I made a logo but i don't know the resolution you want it at.

**Comment by vlad4him** [comment]
I made a logo but i need you to tell me the resolution you wanted at.

**Comment by CedArctic** [comment]
@vlad4him 's logo has been selected. Closing the issue.
